id = "fiberplane-studio-zed"
name = "Fiberplane Studio"
description = "A way to interface with traces captured by the Fiberplane Studio"
version = "0.1.0"
schema_version = 1
authors = ["Fiberplane <info@fiberplane.com>"]
repository = "https://github.com/fiberplane/fpx"

[slash_commands.trace]
description = "Add a trace from the Fiberplane Studio"
requires_argument = true
